#!/usr/bin/env python

import csv
import requests

projects = []
achievements = []

with open("_data/projects.csv") as f:
    lines = f
    lines = f.readlines()

    for l in  csv.reader(lines, quotechar='"', delimiter=',', quoting=csv.QUOTE_ALL, skipinitialspace=True):
        projects.append(l[4])

    projects.pop(0)

with open("_data/achievements.csv") as f:
    lines = f
    lines = f.readlines()

    for l in  csv.reader(lines, quotechar='"', delimiter=',', quoting=csv.QUOTE_ALL, skipinitialspace=True):
        achievements.append(l[4])

    achievements.pop(0)

links = projects + achievements

for url in links:
    print(url)
    try:
        request = requests.get(url)
        if request.status_code == 200:
            print("Web site exists")
    except:
        print("Web site does not exist")
        exit(1)
