#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import csv
import requests

projects_file = "_data/projects.csv"
achievements_file = "_data/achievements.csv"
projects = []
achievements = []
exit_status = 0

print(f"Collecting all URLs from {projects_file}")

with open(projects_file) as f:
    lines = f.readlines()

    for l in  csv.reader(lines, quotechar='"', delimiter=',', quoting=csv.QUOTE_ALL, skipinitialspace=True):
        projects.append(l[4])

    projects.pop(0)

print(f"Collecting all URLs from {achievements_file}")

with open(achievements_file) as f:
    lines = f.readlines()

    for l in  csv.reader(lines, quotechar='"', delimiter=',', quoting=csv.QUOTE_ALL, skipinitialspace=True):
        achievements.append(l[4])

    achievements.pop(0)

links = projects + achievements

print("Checking all URLs")

for url in links:
    try:
        request = requests.get(url)
        if request.status_code == 200:
            print(f"✓ 200 {url}")
        else:
            print(f"✕ {request.status_code} {url}")
    except:
        print(f"✕ ERR {url}")

        # Continue through all URLs but fail test at the end
        exit_status = 1
        continue

exit(exit_status)
