#!/usr/bin/env node
// Generates full route waypoints for route events via OpenRouteService.
// Reads endpoints from src/data/routes.js and writes back waypoints.
//
// Usage: ORS_API_KEY=<key> npm run routes
//   Add --force to regenerate routes that already have waypoints.
//
// Requires Node 18+ (built-in fetch).

import { writeFileSync } from 'fs';
import { fileURLToPath, pathToFileURL } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const force = process.argv.includes('--force');

const ORS_API_KEY = process.env.ORS_API_KEY;
if (!ORS_API_KEY) {
  console.error('Error: ORS_API_KEY environment variable is not set.');
  process.exit(1);
}

// Import routes.js directly — it has no asset imports Node can't handle.
const routesUrl = pathToFileURL(join(root, 'src/data/routes.js')).href;
const { routes } = await import(routesUrl);

// --- OpenRouteService driving-car directions ---

async function fetchRoute(start, end, targetN) {
  const res = await fetch(
    'https://api.openrouteservice.org/v2/directions/driving-car/geojson',
    {
      method: 'POST',
      headers: {
        Authorization: ORS_API_KEY,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        coordinates: [
          [start.lng, start.lat],
          [end.lng, end.lat],
        ],
      }),
    }
  );

  if (!res.ok) {
    throw new Error(`ORS ${res.status}: ${await res.text()}`);
  }

  const geojson = await res.json();
  const raw = geojson.features[0].geometry.coordinates; // [[lng, lat], ...]
  const pts = raw.map(([lng, lat]) => ({
    lat: +lat.toFixed(4),
    lng: +lng.toFixed(4),
  }));

  return decimatePoints(pts, targetN);
}

// Uniform sampling — keeps first, last, and ~targetN evenly spaced points.
function decimatePoints(pts, targetN) {
  if (pts.length <= targetN) return pts;
  const result = [pts[0]];
  const step = (pts.length - 1) / (targetN - 1);
  for (let i = 1; i < targetN - 1; i++) {
    result.push(pts[Math.round(i * step)]);
  }
  result.push(pts[pts.length - 1]);
  return result;
}

// --- Serialize routes.js ---

function serializeRoutes(updated) {
  const header =
    '// Route data keyed by event title.\n' +
    '// `endpoints` — [start, end] used by `npm run routes` to call ORS.\n' +
    '// `waypoints` — full path generated by ORS; null until `npm run routes` is run.\n';

  const entries = Object.entries(updated).map(([title, { points = 50, endpoints, waypoints }]) => {
    const eps = endpoints
      .map(({ lat, lng }) => `    { lat: ${lat}, lng: ${lng} }`)
      .join(',\n');

    const wps = waypoints
      ? waypoints.map(({ lat, lng }) => `    { lat: ${lat}, lng: ${lng} }`).join(',\n')
      : null;

    const waypointsStr = wps ? `[\n${wps},\n  ]` : 'null';

    return (
      `  "${title}": {\n` +
      `    points: ${points},\n` +
      `    endpoints: [\n${eps},\n    ],\n` +
      `    waypoints: ${waypointsStr},\n` +
      `  }`
    );
  });

  const body = `export const routes = {\n${entries.join(',\n')},\n};\n\n` +
    `// Returns the best available coords for a route: full waypoints if generated, else endpoints.\n` +
    `export function route(title) {\n` +
    `  const r = routes[title];\n` +
    `  return r ? (r.waypoints ?? r.endpoints) : null;\n` +
    `}\n`;

  return `${header}\n${body}`;
}

// --- Main ---

const entries = Object.entries(routes);
console.log(`Found ${entries.length} route(s) in routes.js:\n`);

const updated = {};
let generated = 0;

for (const [title, { points = 50, endpoints, waypoints }] of entries) {
  if (!force && waypoints) {
    console.log(`  ✓  ${title} (${waypoints.length} pts, skipping)`);
    updated[title] = { points, endpoints, waypoints };
    continue;
  }
  console.log(`  →  ${title} (${points} pts)`);
  try {
    const [start, end] = endpoints;
    const pts = await fetchRoute(start, end, points);
    console.log(`     ${pts.length} waypoints`);
    updated[title] = { points, endpoints, waypoints: pts };
    generated++;
    // Respect ORS free-tier rate limit (40 req/min)
    await new Promise((r) => setTimeout(r, 1500));
  } catch (err) {
    console.error(`     Failed: ${err.message}`);
    updated[title] = { points, endpoints, waypoints };
  }
}

if (generated > 0) {
  writeFileSync(join(root, 'src/data/routes.js'), serializeRoutes(updated));
  console.log(`\nWrote src/data/routes.js (${generated} route(s) generated).`);
} else {
  console.log('\nAll routes already up to date. Use --force to regenerate.');
}
